# Generated by Django 5.1.4 on 2024-12-31 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_expense_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='account_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
