# Generated by Django 5.1.4 on 2024-12-31 16:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_bankaccount_account_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='expense',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.bankaccount'),
        ),
    ]
