# Generated by Django 5.1.4 on 2024-12-31 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_alter_expense_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='account',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='tracker.bankaccount'),
        ),
    ]
